spring.application.name=mqtt-producer

# kafka (docker network)
spring.kafka.bootstrap-servers=kafka:9092

app.mqtt.broker=tcp://mqtt:1883
app.mqtt.topicFilter=telemetry/#

# kafka topic
app.topics.raw=telemetry.raw

# (??) actuator/metrics ?? ?? ???
management.endpoints.web.exposure.include=health,info,prometheus
management.endpoint.prometheus.enabled=true