spring.application.name=api
server.port=8080

prometheus.base-url=http://prometheus:9090

spring.kafka.bootstrap-servers=kafka:9092
spring.datasource.url=jdbc:postgresql://postgres:5432/telemetry
spring.datasource.username=telemetry
spring.datasource.password=telemetry