{
 "title": "New dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "consumer members",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 0 },
   "targets": [
    { "expr": "kafka_consumergroup_members", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Kafka lag panel",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 5, "x": 4, "y": 0 },
   "targets": [
    {
     "expr": "sum by (consumergroup) (kafka_consumergroup_lag_sum)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "topic별 lag",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 3, "x": 9, "y": 0 },
   "targets": [
    {
     "expr": "sum by (consumergroup, topic) (kafka_consumergroup_lag_sum)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average Processing Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "rate(telemetry_processing_seconds_sum[1m])\r\n/\r\nrate(telemetry_processing_seconds_count[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Telemetry_errors_total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 5 },
   "targets": [
    {
     "expr": "rate(telemetry_errors_total[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Telemetry_dlq_produce_fail_total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "rate(telemetry_dlq_produce_fail_total[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Telemetry_dlq_total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
   "targets": [
    { "expr": "rate(telemetry_dlq_total[1m])", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Telemetry_processed_total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "rate(telemetry_processed_total[1m])",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}